import Layout from '../components/Layout';
import Head from 'next/head';
import Heroo from '../components/home/heroo';
export default function About() {
  return (
    <Layout>
      <Head>
        <title>Portflio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section class="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
        <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <Heroo />
        </div>
      </section>
    </Layout>
  );
}
