import Layout from '../components/Layout';
import Hero from '../components/home/hero';
import Head from 'next/head';

export default function Home() {
  return (
    <Layout title="HJ">
      <Head>
        <title>Portflio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section class="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
        <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <Hero />
        </div>
      </section>
    </Layout>
  );
}
